services:
    ImagineCraft.notifyMinecraft.listener:
        class: ImagineCraft\notifyMinecraft\event\listener
        arguments:
            - @config
        tags:
            - { name: event.listener }
 
